camel:
  springboot:
    # The Camel context name
    name: CamelRestSql

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

mysql:
  service:
    direction: localhost
    port: 3306
    database: sampledb
    user: admin
    password: admin


spring:
  datasource:
    url:      jdbc:mysql://${mysql.service.direction}:${mysql.service.port}/${mysql.service.database}
    usuario: ${mysql.service.username}
    password: ${mysql.service.password}
    classforname: com.mysql.jdbc.Drive 


# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s
