camel:
  springboot:
    # The Camel context name
    name: CamelRestSql

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

mysql:
  service:
    direction: localhost
    port: 3306
    database: sampledb
    user: root
    password: Nuuptech2019!

spring:
  datasource:
    url:      jdbc:mysql://localhost
    usuario: ${mysql.service.user}
    password: ${mysql.service.password}
    classforname: com.mysql.jdbc.Driver 


# The application configuration properties
quickstart:
  generateOrderPeriod: 2s
  processOrderPeriod: 5s
    